### ISSUE TITLE
WebEngage Android SDK release 3.20.1 has breaking changes for this plugin

### ISSUE THREAD

**Issue by hpeinar** [WebEngage/cordova-plugin#12]
[WebEngage Android SDK release 3.20.1](https://docs.webengage.com/docs/changelogs-android#sdk-v3201-april-5-2022) introduces breaking changes for the current latest version (1.0.5) of this plugin.

The cordova-plugin is lacking `onNewSessionStarted() override`

```
WebEngagePlugin.java:52: error: WebEngagePlugin is not abstract and does not override abstract method onNewSessionStarted() in LifeCycleCallbacks
```

**Comment by SarthakWebEngage** [comment]
We have released the changes in 1.1.0. 
Thank you.
