### ISSUE TITLE
ios xcode console error: [WEGConfig refresh] [Line 106] ERROR: Config could not be parsed as json

### ISSUE THREAD

**Issue by guylando** [WebEngage/cordova-plugin#4]
Getting this error on startup in xcode debug console:
[WEGConfig refresh] [Line 106] ERROR: Config could not be parsed as json: Error Domain=NSCOcoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}

**Comment by ashwindmk** [comment]
The above error log indicates that there was some temporary internal server error while fetching/updating configuration from WebEngage server. This should not affect the application.

**Comment by guylando** [comment]
This can't be fixed? I am thinking it affects the performance and am trying to eliminate any errors on app load.

**Comment by ashwindmk** [comment]
This should not affect the app performance in any way as it is executed on a background thread. There was a temporary server-side issue while you received these logs which is already fixed.
If you are still getting these error logs, please update the WebEngage iOS SDK in your app by following the instructions [here](https://docs.webengage.com/docs/cordova-getting-started#section-follow-the-below-steps-for-ios-platform-).

**Comment by guylando** [comment]
Thanks
